loja/urls.py
# Pacote muito interessante para manipulação de URL e query strings
# https://github.com/gruns/furl

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('', include('produto.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# TODO: Remover debug toolbar
if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

perfil/urls.py
from django.urls import path

from . import views


app_name = 'perfil'
urlpatterns = [
    path('', views.Registrar.as_view(), name='registrar'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),

    path('atualizar/', views.Atualizar.as_view(), name='atualizar'),

    # TODO: Atualizar senha
    path('atualizarsenha/', views.AtualizarSenha.as_view(), name='atualizarsenha'),

    path('listaenderecos/', views.ListaEnderecos.as_view(), name='listaenderecos'),
    path('registrarendereco/', views.RegistrarEndereco.as_view(), name='registrarendereco'),
    path('atualizarendereco/<int:pk>/', views.AtualizarEndereco.as_view(), name='atualizarendereco'),
    path('removerendereco/', views.RemoverEndereco.as_view(), name='removerendereco'),
    
    # TODO: Confirmar senha
    path('confirmasenha/', views.ConfirmaSenha.as_view(), name='confirmasenha'),
    
    # path('teste/', views.Teste.as_view(), name='teste'),
]

perfil/models.py
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from utils import functions
from utils.functions import valida_cpf

# para adicionar os erros


class Perfil(models.Model):
    class Meta:
        verbose_name = 'Perfil'
        verbose_name_plural = 'Perfis'

        db_table = 'perfil'

    usuario = models.OneToOneField(
        verbose_name='Usuário', to=User, on_delete=models.CASCADE)
    data_nascimento = models.DateField('Data de nascimento')
    cpf = models.CharField('CPF', max_length=11)

    def __str__(self) -> str:
        return self.usuario.get_full_name() or str(self.usuario)

    # validação a nivel de model
    # https://docs.djangoproject.com/en/3.2/ref/models/instances/#django.db.models.Model.clean
    def clean(self):
        error_list = []

        if not valida_cpf(self.cpf):
            error_list.append({'cpf': 'Digite um CPF válido'})

        if error_list:
            error_list = functions.normalize_error_list(error_list)
            raise ValidationError(error_list)


class Endereco(models.Model):
    class Meta:
        db_table = 'endereco'

    apelido = models.CharField(
        max_length=50, blank=False,
        help_text='Digite aqui um apelido para o endereço. '
        'Ele será usado para você identificar o endereço durante a compra'
    )
    endereco = models.CharField('Endereço', max_length=50)
    numero = models.CharField('Número', max_length=5)
    complemento = models.CharField(max_length=30)
    bairro = models.CharField(max_length=30)
    cep = models.CharField('CEP', max_length=8)
    cidade = models.CharField(max_length=30)
    estado = models.CharField(
        max_length=2,
        default='SP',
        choices=(
            ('AC', 'Acre'),
            ('AL', 'Alagoas'),
            ('AP', 'Amapá'),
            ('AM', 'Amazonas'),
            ('BA', 'Bahia'),
            ('CE', 'Ceará'),
            ('DF', 'Distrito Federal'),
            ('ES', 'Espírito Santo'),
            ('GO', 'Goiás'),
            ('MA', 'Maranhão'),
            ('MT', 'Mato Grosso'),
            ('MS', 'Mato Grosso do Sul'),
            ('MG', 'Minas Gerais'),
            ('PA', 'Pará'),
            ('PB', 'Paraíba'),
            ('PR', 'Paraná'),
            ('PE', 'Pernambuco'),
            ('PI', 'Piauí'),
            ('RJ', 'Rio de Janeiro'),
            ('RN', 'Rio Grande do Norte'),
            ('RS', 'Rio Grande do Sul'),
            ('RO', 'Rondônia'),
            ('RR', 'Roraima'),
            ('SC', 'Santa Catarina'),
            ('SP', 'São Paulo'),
            ('SE', 'Sergipe'),
            ('TO', 'Tocantins'),
        )
    )
    perfil = models.ForeignKey(to=Perfil, on_delete=models.CASCADE)

    def clean(self, *args, **kwargs):
        error_list = []

        apelido_repetido = Endereco.objects.all().filter(apelido=self.apelido).exists()
        if apelido_repetido:
            error_list.append({
                'apelido': 'Você já possui um endereço com este apelido. Escolha outro.'
            })

        if error_list:
            error_list = functions.normalize_error_list(error_list)
            raise ValidationError(error_list)

    def __str__(self):
        return f'{self.apelido}'

perfil/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from utils import functions

from .models import Endereco, Perfil


class RegistrarPerfilForm(forms.ModelForm):
    class Meta:
        model = Perfil
        fields = '__all__'
        exclude = ['usuario']


class RegistrarUsuarioForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        self.fields['email'].required = True

    def clean_email(self):
        data = self.cleaned_data["email"]
        errors = []

        if User.objects.filter(email=data):
            errors.append('Email já cadastrado.')

        if errors:
            raise ValidationError(errors)

        return data


class LoginForm(AuthenticationForm):
    pass


class AtualizarUsuarioForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username']  # , 'email']


class AtualizarPerfilForm(forms.ModelForm):
    class Meta:
        model = Perfil
        exclude = ['usuario']
        # exclude = ['usuario', 'data_nascimento', 'cpf']


# TODO: Formulário de alteração de senha


class RegistrarEnderecoForm(forms.ModelForm):
    class Meta:
        model = Endereco
        exclude = ['perfil']


class AtualizarEnderecoForm(forms.ModelForm):
    class Meta:
        model = Endereco
        exclude = ['perfil']

perfil/views.py
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required
from django.http.request import HttpRequest
from django.http.response import Http404, HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic.list import ListView
from furl import furl
from pedido.views import DispatchLoginRequiredMixin

from . import forms, models

# TODO
# [x] Registrar
# [x] Login
# [x] Logout
# [ ] Atualizar (adicionar o campo email)
# [ ] AtualizarSenha
# [ ] ConfirmaSenha
# [x] ListaEnderecos
# [x] RegistrarEndereco
# [x] AtualizarEndereco
# [x] RemoverEndereco


class BaseRegistrar(View):
    template_name = 'perfil/registrar.html'

    def get_context_data(self, registrarusuarioform=None, registrarperfilform=None, loginform=None, *args, **kwargs):
        """Retorna o contexto com os forms. Se o form foi enviado, retorna o próprio."""
        contexto = {
            'registrarusuarioform': registrarusuarioform or forms.RegistrarUsuarioForm(),
            'registrarperfilform': registrarperfilform or forms.RegistrarPerfilForm(),
            'loginform': loginform or forms.LoginForm(),
        }
        return contexto


class Registrar(BaseRegistrar):
    def get(self, request: HttpRequest, *args, **kwargs):
        if request.user.is_authenticated:
            # TODO: Trocar por redirecionar para o perfil
            return redirect(reverse('produto:carrinho'))

        contexto = self.get_context_data(*args, **kwargs)
        return render(request, self.template_name, contexto)

    def post(self, request: HttpRequest, *args, **kwargs):
        registrarusuarioform = forms.RegistrarUsuarioForm(data=request.POST)
        registrarperfilform = forms.RegistrarPerfilForm(data=request.POST)

        # Formulário válido: Registra o usuário e perfil
        if registrarusuarioform.is_valid() and registrarperfilform.is_valid():
            usuario = registrarusuarioform.save()
            perfil = registrarperfilform.save(commit=False)

            perfil.usuario = usuario
            perfil.save()

            messages.success(
                request,
                'Conta criada com sucesso, agora faça login.'
            )
            return redirect(reverse('perfil:registrar'))

        messages.error(request, 'Existem erros no formulário.')

        # Formulário inválido: Exibe o formulário com os erros
        contexto = self.get_context_data(
            registrarusuarioform=registrarusuarioform,
            registrarperfilform=registrarperfilform,
            *args, **kwargs
        )
        return render(request, self.template_name, contexto)


class Login(BaseRegistrar):
    def post(self, request: HttpRequest, *args, **kwargs):
        http_referer = request.META.get('HTTP_REFERER')

        carrinho = request.session.get('carrinho', {})

        loginform = forms.LoginForm(data=request.POST)

        if loginform.is_valid():
            user = loginform.get_user()
            auth.login(request, user)

            # copia o carrinho da sessão anterior
            request.session['carrinho'] = carrinho

            return redirect(
                request.GET.get(
                    'redirect_url', reverse('produto:listaprodutos')
                )
            )

        messages.error(request, 'Existem erros no formulário.')

        contexto = self.get_context_data(loginform=loginform, *args, **kwargs)
        return render(request, self.template_name, contexto)


@method_decorator(login_required, name='dispatch')
class Logout(View):
    def get(self, request: HttpRequest, *args, **kwargs):
        carrinho = request.session.get('carrinho', {})

        auth.logout(request)

        # copia o carrinho da sessão anterior
        request.session['carrinho'] = carrinho

        return redirect(reverse('produto:listaprodutos'))


# decorando classes com login_required
# https://docs.djangoproject.com/en/3.2/topics/class-based-views/intro/#decorating-class-based-views
@method_decorator(login_required, name='dispatch')
class Atualizar(View):
    template_name = 'perfil/atualizar.html'

    def get_context_data(self, *args, **kwargs):
        """Retorna o contexto com os forms."""

        usuario = self.request.user

        perfil = None
        if hasattr(usuario, 'perfil'):
            perfil = usuario.perfil

        contexto = {
            'atualizarusuarioform': forms.AtualizarUsuarioForm(
                data=self.request.POST or None,
                instance=usuario,
            ),
            'atualizarperfilform': forms.AtualizarPerfilForm(
                data=self.request.POST or None,
                instance=perfil,
            ),
        }

        return contexto

    def get(self, request: HttpRequest, *args, **kwargs):
        contexto = self.get_context_data(*args, **kwargs)
        return render(request, self.template_name, contexto)

    def post(self, request: HttpRequest, *args, **kwargs):
        contexto = self.get_context_data(*args, **kwargs)

        atualizarusuarioform = contexto['atualizarusuarioform']
        atualizarperfilform = contexto['atualizarperfilform']

        if atualizarusuarioform.is_valid() and atualizarperfilform.is_valid():
            # TODO: Para atualizar deve-se antes confirmar a senha
            usuario = atualizarusuarioform.save()
            perfil = atualizarperfilform.save(commit=False)

            perfil.usuario = usuario

            perfil.save()

            messages.success(request, 'Dados alterados com sucesso.')

            if 'username' in atualizarusuarioform.changed_data:
                auth.logout(request)
                messages.success(
                    request,
                    'Nome de usuário alterado com sucesso. '
                    'Faça login novamente.'
                )
                return redirect(reverse('perfil:registrar'))

            # BUG: Quando adiciona o campo email ao formulário em contexto
            # é levantada exceção.
            # O campo email está desativado e para ativar basta adicionar
            # email aos fields do form do usuario
            return redirect(reverse('perfil:atualizar'))

        messages.error(request, 'Existem erros no formulário.')
        return render(request, self.template_name, self.get_context_data())


@method_decorator(login_required, name='dispatch')
class AtualizarSenha(View):
    template_name = 'perfil/atualizarsenha.html'

    def get(self, request: HttpRequest, *args, **kwargs):
        return render(request, self.template_name)


@method_decorator(login_required, name='dispatch')
class ConfirmaSenha(View):
    def get(self, request: HttpRequest, *args, **kwargs):
        return render(request, 'perfil/confirmasenha.html')


class ListaEnderecos(DispatchLoginRequiredMixin, ListView):
    model = models.Endereco
    template_name = 'perfil/listaenderecos.html'
    context_object_name = 'enderecos'
    paginate_by = 10

    def get_queryset(self):
        qs = super().get_queryset().filter(
            perfil_id=self.request.user.perfil.pk
        ).order_by(
            'estado'
        )
        return qs


class RegistrarEndereco(DispatchLoginRequiredMixin, View):
    template_name = 'perfil/registrarendereco.html'

    def get_context_data(self, *args, **kwargs):
        contexto = {
            'registrarenderecoform': forms.RegistrarEnderecoForm(
                data=self.request.POST or None,
            )
        }
        return contexto

    def get(self, request: HttpRequest, *args, **kwargs):
        contexto = self.get_context_data(*args, **kwargs)
        return render(request, self.template_name, contexto)

    def post(self, request: HttpRequest, *args, **kwargs):
        contexto = self.get_context_data(*args, **kwargs)
        registrarenderecoform = contexto['registrarenderecoform']

        if registrarenderecoform.is_valid():
            endereco = registrarenderecoform.save(commit=False)
            perfil = request.user.perfil
            endereco.perfil = perfil
            endereco.save()
            messages.success(request, 'Endereço registrado com sucesso')
            return redirect(reverse('perfil:listaenderecos'))

        messages.error(request, 'Existem erros no formulário.')

        return render(request, self.template_name, contexto)


class AtualizarEndereco(DispatchLoginRequiredMixin, View):
    template_name = 'perfil/atualizarendereco.html'

    def get_context_data(self, *args, **kwargs):
        endereco_id = kwargs.get('pk')
        endereco = models.Endereco.objects.filter(pk=endereco_id).first()
        contexto = {
            'atualizarenderecoform': forms.AtualizarEnderecoForm(
                data=self.request.POST or None,
                instance=endereco
            )
        }
        return contexto

    def get(self, request: HttpRequest, *args, **kwargs):
        contexto = self.get_context_data(*args, **kwargs)
        return render(request, self.template_name, contexto)

    def post(self, request: HttpRequest, *args, **kwargs):
        contexto = self.get_context_data(*args, **kwargs)

        atualizarenderecoform = contexto['atualizarenderecoform']

        if atualizarenderecoform.is_valid():
            atualizarenderecoform.save()
            messages.success(request, 'Endereço editado com sucesso.')

            return redirect(reverse('perfil:listaenderecos'))

        messages.error(request, 'Existem erros no formulário.')

        return render(request, self.template_name, contexto)


class RemoverEndereco(DispatchLoginRequiredMixin, View):
    http_method_names = ['get']
    template_name = 'perfil/removerendereco.html'

    def get(self, request: HttpRequest, *args, **kwargs):
        endereco_id = request.GET.get('eid')

        if endereco_id:
            models.Endereco.objects.filter(pk=endereco_id).delete()

perfil/templates/perfil/atualizar.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block titulo %}Alterar cadastro | {% endblock %}

{% block conteudo %}
<div class="row">
    <div class="col-lg">
        <h1>Alterar cadastro</h1>
        <form method="post" action="{% url 'perfil:atualizar' %}">
            {% csrf_token %}
            {{ atualizarusuarioform|crispy }}
            {{ atualizarperfilform|crispy }}
            <button type="submit" class="btn btn-primary btn-block btn-lg">
                Salvar
            </button>
        </form>
    </div>
</div>
{% endblock %}

perfil/templates/perfil/atualizarendereco.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block titulo %}Alterar endereço | {% endblock %}

{% block conteudo %}
<div class="row">
    <div class="col-lg">
        <h1>Atualizar endereço</h1>
        <form method="post" action="">
            {% csrf_token %}
            {{ atualizarenderecoform|crispy }}
            <button type="submit" class="btn btn-primary btn-block btn-lg">
                Salvar
            </button>
        </form>
    </div>
</div>
{% endblock %}

perfil/templates/perfil/atualizarsenha.html
atualizarsenha.html

perfil/templates/perfil/confirmasenha.html
confirmasenha.html

perfil/templates/perfil/listaenderecos.html
{% extends 'base.html' %}

{% load vffilters %}

{% block titulo %}Endereços | {% endblock %}

{% block conteudo %}
{% if enderecos %}
<div class="row mt-3">
    <div class="col">
        <h3>Endereços</h3>
        <div class="table-responsive">
            <table class="table">
                <tr>
                    <th class="d-none d-lg-block">Apelido</th>
                    <th>Estado</th>
                    <th>Cidade</th>
                    <th>CEP</th>
                    <th>Bairro</th>
                    <th>Complemento</th>
                    <th>Número</th>
                    <th>Endereço</th>
                    <th>Editar</th>
                    <th>Apagar</th>
                </tr>
                {% for endereco in enderecos %}
                <tr>
                    <td>{{ endereco.apelido }}</td>
                    <td>{{ endereco.estado }}</td>
                    <td>{{ endereco.cidade }}</td>
                    <td>{{ endereco.cep }}</td>
                    <td>{{ endereco.bairro }}</td>
                    <td>{{ endereco.complemento }}</td>
                    <td>{{ endereco.numero }}</td>
                    <td>{{ endereco.endereco }}</td>
                    <td>
                        <a href="{% url 'perfil:atualizarendereco' endereco.pk %}">
                            <i class="fas fa-edit"></i>
                        </a>
                    </td>
                    <td>
                        <form method="get" action="{% url 'perfil:removerendereco' %}">
                            <input type="hidden" name="eid" value="{{ endereco.pk }}">
                            <button type="submit" class="btn pl-0 pr-3">
                                <i class="ml-3 fas fa-times-circle text-danger"></i>
                            </button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>

        {% include 'includes/_pagination.html' %}

        <div class="col-lg mt-auto">
            <a class="btn btn-lg btn-block btn-primary" href="{% url 'perfil:registrarendereco' %}">
                Novo endereço
            </a>
        </div>
    </div>
</div>
{% else %}
<div class="row mt-3">
    <div class="col">
        <h3>Sem endereços</h3>
        <p class="lead">Não há endereços registrados. Clique
            <a href="{% url 'perfil:registrarendereco' %}">aqui</a> para registrar.
        </p>
    </div>
</div>
{% endif %}
{% endblock %}

perfil/templates/perfil/registrar.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block titulo %}Login | {% endblock %}

{% block conteudo %}
<div class="row">
    <div class="col-lg">
        <h1>Login</h1>
        <form method="post" action="{% url 'perfil:login' %}">
            {% csrf_token %}
            {{ loginform|crispy }}
            <button type="submit" class="btn btn-primary btn-block btn-lg">
                Entrar
            </button>
        </form>
    </div>
    <div class="col-lg">
        <h1>Cadastro</h1>
        <form method="post" action="{% url 'perfil:registrar' %}">
            {% csrf_token %}
            {{ registrarusuarioform|crispy }}
            {{ registrarperfilform|crispy }}
            <button type="submit" class="btn btn-primary btn-block btn-lg">
                Cadastrar
            </button>
        </form>
    </div>
</div>
{% endblock %}

perfil/templates/perfil/registrarendereco.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block titulo %}Registrar endereço | {% endblock %}

{% block conteudo %}
<div class="row">
    <div class="col-lg">
        <h1>Registrar endereço</h1>
        <form method="post" action="{% url 'perfil:registrarendereco' %}">
            {% csrf_token %}
            {{ registrarenderecoform|crispy }}
            <button type="submit" class="btn btn-primary btn-block btn-lg">
                Salvar
            </button>
        </form>
    </div>
</div>
{% endblock %}