loja/urls.py
# Pacote muito interessante para manipulação de URL e query strings
# https://github.com/gruns/furl

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('', include('produto.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# TODO: Remover debug toolbar
if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

pedido/urls.py
from django.urls import path

from . import views


app_name = 'pedido'
urlpatterns = [
    path('pagar/<int:pk>/', views.Pagar.as_view(), name='pagar'),
    path('listapedidos/', views.ListaPedidos.as_view(), name='listapedidos'),
    path('salvarpedido/', views.SalvarPedido.as_view(), name='salvarpedido'),
    path('detalhe/<int:pk>/', views.Detalhe.as_view(), name='detalhe'),
]

perfil/urls.py
from django.urls import path

from . import views


app_name = 'perfil'
urlpatterns = [
    path('', views.Registrar.as_view(), name='registrar'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),

    path('atualizar/', views.Atualizar.as_view(), name='atualizar'),

    # TODO: Atualizar senha
    path('atualizarsenha/', views.AtualizarSenha.as_view(), name='atualizarsenha'),

    path('listaenderecos/', views.ListaEnderecos.as_view(), name='listaenderecos'),
    path('registrarendereco/', views.RegistrarEndereco.as_view(), name='registrarendereco'),
    path('atualizarendereco/<int:pk>/', views.AtualizarEndereco.as_view(), name='atualizarendereco'),
    path('removerendereco/', views.RemoverEndereco.as_view(), name='removerendereco'),
    
    # TODO: Confirmar senha
    path('confirmasenha/', views.ConfirmaSenha.as_view(), name='confirmasenha'),
    
    # path('teste/', views.Teste.as_view(), name='teste'),
]

produto/urls.py
from django.urls import path

from . import views


app_name = 'produto'
urlpatterns = [
    path('', views.ListaProdutos.as_view(), name='listaprodutos'),
    path('detalheproduto/<slug:slug>/',
         views.DetalheProduto.as_view(), name='detalheproduto'),
    path('adicionaraocarrinho/', views.AdicionarAoCarrinho.as_view(),
         name='adicionaraocarrinho'),
    path('removerdocarrinho/', views.RemoverDoCarrinho.as_view(),
         name='removerdocarrinho'),
    path('carrinho/', views.Carrinho.as_view(), name='carrinho'),
    path('resumodacompra/', views.ResumoDaCompra.as_view(), name='resumodacompra'),
    path('busca/', views.Busca.as_view(), name='busca'),
]

pedido/models.py
from django.db import models
from perfil.models import Perfil


class Pedido(models.Model):
    class Meta:
        db_table = 'pedido'

    usuario = models.ForeignKey(
        verbose_name='Usuário', to=Perfil, on_delete=models.CASCADE)
    total = models.FloatField()
    qtd_total = models.PositiveIntegerField()
    status = models.CharField(
        default='C',
        max_length=1,
        choices=(
            ('A', 'Aprovado'),
            ('C', 'Criado'),
            ('R', 'Reprovado'),
            ('P', 'Pendente'),
            ('E', 'Enviado'),
            ('F', 'Finalizado')
        )
    )

    def __str__(self) -> str:
        return f'Pedido N. {self.pk}'


class ItemPedido(models.Model):
    class Meta:
        verbose_name = 'Item do pedido'
        verbose_name_plural = 'Itens do pedido'

        db_table = 'itempedido'

    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    produto = models.CharField(max_length=255)
    produto_id = models.PositiveIntegerField()
    variacao = models.CharField('Variação', max_length=255)
    variacao_id = models.PositiveIntegerField('ID da Variação')
    preco = models.FloatField('Preço')
    preco_promocional = models.FloatField('Preço promocional', default=0)
    quantidade = models.PositiveIntegerField()
    imagem = models.CharField(max_length=2048)

    def __str__(self) -> str:
        return f'Item do {self.pedido}'

pedido/views.py
from django.contrib import messages
from django.http.request import HttpRequest
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views import View
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from produto.models import Variacao
from produto.views import CarrinhoMixin
from utils import functions
from utils.mixins import DispatchLoginRequiredMixin

from . import models


class Pagar(DispatchLoginRequiredMixin, DetailView):
    template_name = 'pedido/pagar.html'
    model = models.Pedido
    pk_url_kwarg = 'pk'
    context_object_name = 'pedido'

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(usuario_id=self.request.user.perfil.pk)
        return qs


class ListaPedidos(DispatchLoginRequiredMixin, ListView):
    model = models.Pedido
    context_object_name = 'pedidos'
    paginate_by = 15
    template_name = 'pedido/listapedidos.html'
    ordering = '-id'

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(usuario_id=self.request.user.perfil.pk)
        return qs


class SalvarPedido(DispatchLoginRequiredMixin, CarrinhoMixin, View):
    template_name = 'pedido/salvarpedido.html'

    def get(self, request: HttpRequest, *args, **kwargs):
        if not self.get_carrinho():
            messages.error(request, 'Carrinho vazio.')
            return redirect('produto:listaprodutos')

        carrinho: dict = self.get_carrinho()
        carrinho_variacao_ids = list(carrinho.keys())

        bd_variacoes = list(
            Variacao.objects.filter(id__in=carrinho_variacao_ids)
        )

        for variacao in bd_variacoes:
            vid = str(variacao.id)
            estoque = variacao.estoque
            qtd_carrinho = carrinho[vid]['quantidade']
            preco_unt = carrinho[vid]['preco_unitario']
            preco_unt_promo = carrinho[vid]['preco_unitario_promocional']

            if estoque < qtd_carrinho:
                carrinho[vid]['quantidade'] = estoque
                messages.error(
                    request,
                    'Estoque insuficiente para alguns '
                    'produtos do seu carrinho. Reduzimos a '
                    'quantidade desses produtos. Por favor, '
                    'verifique quais produtos foram afetados'
                    ' a seguir.'
                )

        self.atualiza_precos_carrinho()
        self.salva_carrinho()

        qtd_total_carrinho = functions.qtd_total_carrinho(carrinho)
        valor_total_carrinho = functions.calcula_total_carrinho(carrinho)

        pedido = models.Pedido(
            usuario=request.user.perfil,
            total=valor_total_carrinho,
            qtd_total=qtd_total_carrinho,
            status='C',
        )
        pedido.save()

        models.ItemPedido.objects.bulk_create(
            [
                models.ItemPedido(
                    pedido=pedido,
                    produto=v['produto_nome'],
                    produto_id=v['produto_id'],
                    variacao=v['variacao_nome'],
                    variacao_id=v['variacao_id'],
                    preco=v['preco_quantitativo'],
                    preco_promocional=v['preco_quantitativo_promocional'],
                    quantidade=v['quantidade'],
                    imagem=v['imagem'],
                ) for v in carrinho.values()
            ]
        )

        del request.session['carrinho']
        # return render(request, self.template_name)
        return redirect(
            reverse('pedido:pagar', kwargs={'pk': pedido.pk})
        )


class Detalhe(DispatchLoginRequiredMixin, DetailView):
    template_name = 'pedido/detalhe.html'
    model = models.Pedido
    pk_url_kwarg = 'pk'
    context_object_name = 'pedido'

templates/includes/_carrinho.html
{% load vffilters %}

<div class="table-responsive">
    <table class="table">
        <tr>
            <th class="d-none d-lg-block">Imagem</th>
            <th>Produto</th>
            <th>V.</th>
            <th>QTD.</th>
            <th>Total</th>
        </tr>
        {% for k, linha in request.session.carrinho.items %}
        <tr>
            <td class="d-none d-lg-block">
                <img class="cart-img" src="{{ linha.imagem }}">
            </td>
            <td>
                <a href="{% url 'produto:detalheproduto' linha.slug %}">
                    {{ linha.produto_nome }}
                </a>
                <form method="get" action="{% url 'produto:removerdocarrinho' %}">
                    <input type="hidden" name="vid" value="{{ linha.variacao_id }}">
                    <button type="submit" class="btn pl-0 pr-3">
                        <i class="ml-3 fas fa-times-circle text-danger"></i>
                    </button>
                </form>
            </td>
            <td>{{ linha.variacao_nome }}</td>

            {% if linha.preco_quantitativo_promocional %}
            <td>{{ linha.quantidade }} x {{ linha.preco_unitario_promocional|formata_dinheiro }}</td>
            <td>{{ linha.preco_quantitativo_promocional|formata_dinheiro }}</td>
            {% else %}
            <td>{{ linha.quantidade }} x {{ linha.preco_unitario|formata_dinheiro }}</td>
            <td>{{ linha.preco_quantitativo|formata_dinheiro }}</td>
            {% endif %}
        </tr>
        {% endfor %}
    </table>
</div>

templates/includes/_footer.html
{% load static %}

<footer class="container-fluid bg-primary">
    <div class="container text-light">
        <div class="row">
            <div class="col">
                <div class="p-1">
                    <span class="align-middle p-1">Feito com Django</span>
                </div>
            </div>
            <div class="col">
                <div class="p-1 text-right">
                    <span class="align-middle p-1">Por Luiz Otávio</span>
                </div>
            </div>
        </div>
    </div>
</footer>

<script src="{% static 'assets/bootstrap/js/jquery-3.2.1.slim.min.js' %}"></script>
<script src="{% static 'assets/bootstrap/js/popper.min.js' %}"></script>
<script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
<script defer src="{% static 'assets/font-awesome/js/all.js' %}"></script>
<script src="{% static 'assets/custom/js/scripts.js' %}"></script>

templates/includes/_head.html
{% load static %}

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'assets/custom/css/style.css' %}">

templates/includes/_messages.html
{% if messages %}
    <br>
    {% for message in messages %}
        <div class="alert {{ message.tags }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/includes/_nav.html
{% load vffilters %}

<nav class="navbar navbar-dark bg-primary navbar-expand-lg">
    <a class="navbar-brand" href="{% url 'produto:listaprodutos' %}">Loja</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            {% if request.user.is_authenticated %}
            <!-- TODO: Adicionar as opções para o usuário logado -->
            <li class="nav-item active">
                <a class="nav-link" href="#">Opção<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown active">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    Opções
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'pedido:listapedidos' %}">Meus pedidos</a>
                    <a class="dropdown-item" href="{% url 'perfil:listaenderecos' %}">Meus endereços</a>
                    <a class="dropdown-item" href="{% url 'perfil:atualizar' %}">Alterar cadastro</a>
                    <a class="dropdown-item" href="{% url 'perfil:atualizarsenha' %}">Alterar senha</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'perfil:logout' %}">Sair</a>
                </div>
            </li>
            {% else %}
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'perfil:registrar' %}">Entrar<span class="sr-only">(current)</span></a>
            </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link disabled" href="#">Disabled</a>
            </li>
            {% if request.session.carrinho|length %}
            <li class="nav-item">
                <a class="nav-link nav-cart-link active" href="{% url 'produto:carrinho' %}">
                    <span class="nav-cart-text mr-1">
                        Carrinho
                    </span>
                    <span class="nav-cart-count mr-1">
                        <strong>{{ request.session.carrinho|qtd_total_carrinho }}x</strong>
                    </span>
                    <span class="nav-cart-icon mr-2">
                        <i class="fas fa-shopping-cart"></i>
                    </span>
                </a>
            </li>
            {% endif %}
        </ul>
        <form method="get" action="{% url 'produto:busca' %}" class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" value="{{ request.GET.termo }}" type="search" placeholder="Busca"
                aria-label="Busca" name="termo">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Busca</button>
        </form>
    </div>
</nav>

templates/includes/_pagination.html
{% if is_paginated %}
<div class="col mt-3 mb-3">
    <div class="row">
        <div class="pagination">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">&laquo;</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lsaquo;</a>
                </li>
                {% endif %}

                {% for num in page_obj.paginator.page_range %}

                {% if page_obj.number == num %}
                <li class="page-item active">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
                {% endif %}

                {% endfor %}

                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">&rsaquo;</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endif %}

templates/includes/_pedido.html
{% load vffilters %}

<div class="row">
    <div class="col">
        <h3>Pedido N. {{ pedido.pk }}</h3>
        <div class="row mt-4">
            <div class="col-lg-2 font-weight-bold">Número do pedido:</div>
            <div class="col-lg-4">{{ pedido.pk }}</div>
            <div class="col-lg-2 font-weight-bold">Total a pagar:</div>
            <div class="col-lg-4">{{ pedido.total|formata_dinheiro }}</div>
            <div class="col-lg-2 font-weight-bold">QTD. Itens:</div>
            <div class="col-lg-4">{{ pedido.qtd_total }}</div>
            <div class="col-lg-2 font-weight-bold">Status:</div>
            <div class="col-lg-4">{{ pedido.get_status_display }}</div>
        </div>
        <div class="row mt-4">
            <div class="col">
                <h3>Produtos</h3>
            </div>
        </div>
        <div class="table-responsive mt-3">
            <table class="table">
                <tr>
                    <th class="d-none d-lg-block">Imagem</th>
                    <th>Produto</th>
                    <th>V.</th>
                    <th>QTD.</th>
                    <th>Total</th>
                </tr>
                {% for linha in pedido.itempedido_set.all %}
                <tr>
                    <td class="d-none d-lg-block">
                        <img class="cart-img" src="{{ linha.imagem }}">
                    </td>
                    <td>{{ linha.produto }}</td>
                    <td>{{ linha.variacao }}</td>
                    <td>{{ linha.quantidade }}</td>
                    {% if linha.preco_promocional %}
                    <td>{{ linha.preco_promocional|formata_dinheiro }}</td>
                    {% else %}
                    <td>{{ linha.preco|formata_dinheiro }}</td>
                    {% endif %}
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>