loja/urls.py
# Pacote muito interessante para manipulação de URL e query strings
# https://github.com/gruns/furl

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('', include('produto.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# TODO: Remover debug toolbar
if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

pedido/urls.py
from django.urls import path

from . import views


app_name = 'pedido'
urlpatterns = [
    path('pagar/<int:pk>/', views.Pagar.as_view(), name='pagar'),
    path('listapedidos/', views.ListaPedidos.as_view(), name='listapedidos'),
    path('salvarpedido/', views.SalvarPedido.as_view(), name='salvarpedido'),
    path('detalhe/<int:pk>/', views.Detalhe.as_view(), name='detalhe'),
]

pedido/models.py
from django.db import models
from perfil.models import Perfil


class Pedido(models.Model):
    class Meta:
        db_table = 'pedido'

    usuario = models.ForeignKey(
        verbose_name='Usuário', to=Perfil, on_delete=models.CASCADE)
    total = models.FloatField()
    qtd_total = models.PositiveIntegerField()
    status = models.CharField(
        default='C',
        max_length=1,
        choices=(
            ('A', 'Aprovado'),
            ('C', 'Criado'),
            ('R', 'Reprovado'),
            ('P', 'Pendente'),
            ('E', 'Enviado'),
            ('F', 'Finalizado')
        )
    )

    def __str__(self) -> str:
        return f'Pedido N. {self.pk}'


class ItemPedido(models.Model):
    class Meta:
        verbose_name = 'Item do pedido'
        verbose_name_plural = 'Itens do pedido'

        db_table = 'itempedido'

    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    produto = models.CharField(max_length=255)
    produto_id = models.PositiveIntegerField()
    variacao = models.CharField('Variação', max_length=255)
    variacao_id = models.PositiveIntegerField('ID da Variação')
    preco = models.FloatField('Preço')
    preco_promocional = models.FloatField('Preço promocional', default=0)
    quantidade = models.PositiveIntegerField()
    imagem = models.CharField(max_length=2048)

    def __str__(self) -> str:
        return f'Item do {self.pedido}'

pedido/views.py
from django.contrib import messages
from django.http.request import HttpRequest
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views import View
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from produto.models import Variacao
from produto.views import CarrinhoMixin
from utils import functions
from utils.mixins import DispatchLoginRequiredMixin

from . import models


class Pagar(DispatchLoginRequiredMixin, DetailView):
    template_name = 'pedido/pagar.html'
    model = models.Pedido
    pk_url_kwarg = 'pk'
    context_object_name = 'pedido'

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(usuario_id=self.request.user.perfil.pk)
        return qs


class ListaPedidos(DispatchLoginRequiredMixin, ListView):
    model = models.Pedido
    context_object_name = 'pedidos'
    paginate_by = 15
    template_name = 'pedido/listapedidos.html'
    ordering = '-id'

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(usuario_id=self.request.user.perfil.pk)
        return qs


class SalvarPedido(DispatchLoginRequiredMixin, CarrinhoMixin, View):
    template_name = 'pedido/salvarpedido.html'

    def get(self, request: HttpRequest, *args, **kwargs):
        if not self.get_carrinho():
            messages.error(request, 'Carrinho vazio.')
            return redirect('produto:listaprodutos')

        carrinho: dict = self.get_carrinho()
        carrinho_variacao_ids = list(carrinho.keys())

        bd_variacoes = list(
            Variacao.objects.filter(id__in=carrinho_variacao_ids)
        )

        for variacao in bd_variacoes:
            vid = str(variacao.id)
            estoque = variacao.estoque
            qtd_carrinho = carrinho[vid]['quantidade']
            preco_unt = carrinho[vid]['preco_unitario']
            preco_unt_promo = carrinho[vid]['preco_unitario_promocional']

            if estoque < qtd_carrinho:
                carrinho[vid]['quantidade'] = estoque
                messages.error(
                    request,
                    'Estoque insuficiente para alguns '
                    'produtos do seu carrinho. Reduzimos a '
                    'quantidade desses produtos. Por favor, '
                    'verifique quais produtos foram afetados'
                    ' a seguir.'
                )

        self.atualiza_precos_carrinho()
        self.salva_carrinho()

        qtd_total_carrinho = functions.qtd_total_carrinho(carrinho)
        valor_total_carrinho = functions.calcula_total_carrinho(carrinho)

        pedido = models.Pedido(
            usuario=request.user.perfil,
            total=valor_total_carrinho,
            qtd_total=qtd_total_carrinho,
            status='C',
        )
        pedido.save()

        models.ItemPedido.objects.bulk_create(
            [
                models.ItemPedido(
                    pedido=pedido,
                    produto=v['produto_nome'],
                    produto_id=v['produto_id'],
                    variacao=v['variacao_nome'],
                    variacao_id=v['variacao_id'],
                    preco=v['preco_quantitativo'],
                    preco_promocional=v['preco_quantitativo_promocional'],
                    quantidade=v['quantidade'],
                    imagem=v['imagem'],
                ) for v in carrinho.values()
            ]
        )

        del request.session['carrinho']
        # return render(request, self.template_name)
        return redirect(
            reverse('pedido:pagar', kwargs={'pk': pedido.pk})
        )


class Detalhe(DispatchLoginRequiredMixin, DetailView):
    template_name = 'pedido/detalhe.html'
    model = models.Pedido
    pk_url_kwarg = 'pk'
    context_object_name = 'pedido'

pedido/templates/pedido/detalhe.html
{% extends 'base.html' %}

{% block titulo %}Pedido N. {{ pedido.pk }} | {% endblock %}

{% block conteudo %}
{% include 'includes/_pedido.html' %}
{% endblock %}

pedido/templates/pedido/listapedidos.html
{% extends 'base.html' %}

{% load vffilters %}

{% block titulo %}Pedidos | {% endblock %}

{% block conteudo %}
<div class="row">
    <div class="col">
        <h3 class="mb-4">Meus pedidos</h3>
        <p>Abaixo todos os seus pedidos realizados na loja.</p>

        <div class="table-responsive">
            <table class="table table-striped">
                <tr>
                    <th scope="col">Pedido</th>
                    <th scope="col">Total</th>
                    <th scope="col">Qtd. Itens</th>
                    <th scope="col">Status</th>
                    <th scope="col">Mais detalhes</th>
                </tr>
                {% for pedido in pedidos %}
                <tr>
                    <th scope="row">{{ pedido }}</td>
                    <td>{{ pedido.total|formata_dinheiro }}</td>
                    <td>{{ pedido.qtd_total }}</td>
                    <td>{{ pedido.get_status_display }}</td>
                    <td>
                        <a href="{% url 'pedido:detalhe' pedido.pk %}">
                            Ver <i class="fas fa-search-plus ml-2"></i>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
{% include 'includes/_pagination.html' %}
{% endblock %}

pedido/templates/pedido/pagar.html
{% extends 'base.html' %}

{% load vffilters %}

{% block titulo %}Pagar | {% endblock %}

{% block conteudo %}
<div class="row">
    <div class="col">
        <h3>Escolha o método de pagamento</h3>
        <p>Para o desenvolvedor: adicione seu método de pagamento preferido.</p>
    </div>
</div>
{% include 'includes/_pedido.html' %}
<div class="row mt-4">
    <div class="col">
        <a href="#" class="btn btn-primary btn-block btn-lg">Pagar</a>
    </div>
</div>
{% endblock %}

pedido/templates/pedido/salvarpedido.html
salvarpedido.html