loja/urls.py
# Pacote muito interessante para manipulação de URL e query strings
# https://github.com/gruns/furl

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('', include('produto.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# TODO: Remover debug toolbar
if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

pedido/urls.py
from django.urls import path

from . import views


app_name = 'pedido'
urlpatterns = [
    path('pagar/<int:pk>/', views.Pagar.as_view(), name='pagar'),
    path('listapedidos/', views.ListaPedidos.as_view(), name='listapedidos'),
    path('salvarpedido/', views.SalvarPedido.as_view(), name='salvarpedido'),
    path('detalhe/<int:pk>/', views.Detalhe.as_view(), name='detalhe'),
]

perfil/urls.py
from django.urls import path

from . import views


app_name = 'perfil'
urlpatterns = [
    path('', views.Registrar.as_view(), name='registrar'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),

    path('atualizar/', views.Atualizar.as_view(), name='atualizar'),

    # TODO: Atualizar senha
    path('atualizarsenha/', views.AtualizarSenha.as_view(), name='atualizarsenha'),

    path('listaenderecos/', views.ListaEnderecos.as_view(), name='listaenderecos'),
    path('registrarendereco/', views.RegistrarEndereco.as_view(), name='registrarendereco'),
    path('atualizarendereco/<int:pk>/', views.AtualizarEndereco.as_view(), name='atualizarendereco'),
    path('removerendereco/', views.RemoverEndereco.as_view(), name='removerendereco'),
    
    # TODO: Confirmar senha
    path('confirmasenha/', views.ConfirmaSenha.as_view(), name='confirmasenha'),
    
    # path('teste/', views.Teste.as_view(), name='teste'),
]

produto/urls.py
from django.urls import path

from . import views


app_name = 'produto'
urlpatterns = [
    path('', views.ListaProdutos.as_view(), name='listaprodutos'),
    path('detalheproduto/<slug:slug>/',
         views.DetalheProduto.as_view(), name='detalheproduto'),
    path('adicionaraocarrinho/', views.AdicionarAoCarrinho.as_view(),
         name='adicionaraocarrinho'),
    path('removerdocarrinho/', views.RemoverDoCarrinho.as_view(),
         name='removerdocarrinho'),
    path('carrinho/', views.Carrinho.as_view(), name='carrinho'),
    path('resumodacompra/', views.ResumoDaCompra.as_view(), name='resumodacompra'),
    path('busca/', views.Busca.as_view(), name='busca'),
]

produto/models.py
from django.db import models
from django.utils.text import slugify
from PIL import Image


class Produto(models.Model):
    class Meta:
        db_table = 'produto'

    nome = models.CharField(max_length=255)
    descricao_curta = models.TextField('Descrição curta', max_length=255)
    descricao_longa = models.TextField('Descrição longa')
    imagem = models.ImageField(
        upload_to='produto_imagens/%Y/%m/', blank=True, null=True)
    slug = models.SlugField(max_length=255, unique=True, blank=True, null=True)
    tipo = models.CharField(
        default='V',
        max_length=1,
        choices=(
            ('V', 'Variação'),
            ('S', 'Simples')
        )
    )

    def __str__(self) -> str:
        return self.nome

    def save(self, *args, **kwargs) -> None:
        if self.slug is None or not self.slug:
            self.slug = f'{slugify(self.nome)}'

        super().save(*args, **kwargs)

        self.resize_image(self.imagem)

    @staticmethod
    def resize_image(img: models.ImageField, new_width: int = 800) -> None:
        if not img:
            return

        # TODO: pesquisar sobre img.file, mais especificamente se há problema
        # em usar .close() nele
        with Image.open(img.path) as pil_img:
            old_width, old_height = pil_img.size

            if old_width > new_width:
                new_height = round(new_width * old_height / old_width)

                pil_img.resize(
                    (new_width, new_height), Image.LANCZOS
                ).save(
                    img.path, optimize=True, quality=50
                )


class Variacao(models.Model):
    class Meta:
        verbose_name = 'Variação'
        verbose_name_plural = 'Variações'

        db_table = 'variacao'

    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    nome = models.CharField(max_length=50)
    preco = models.FloatField('Preço')
    preco_promocional = models.FloatField('Preço promocional', default=0)
    estoque = models.PositiveIntegerField(default=1)

    def __str__(self) -> str:
        return self.nome

produto/views.py
from utils.mixins import DispatchLoginRequiredMixin
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http.request import HttpRequest
from django.http.response import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.utils.http import urlencode
from django.views import View
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from perfil.models import Endereco
from furl import furl
from django.utils.safestring import mark_safe
from django.db.models import Q

from . import models
from .exceptions import SemEstoqueError

# TODO
# [x] ListaProdutos
# [x] DetalheProduto
# [x] Carrinho
# [x] AdicionarAoCarrinho
# [x] RemoverDoCarrinho
# [x] ResumoDaCompra


class CarrinhoMixin:
    def get_carrinho(self):
        """Retorna o carrinho."""
        if not self.request.session.get('carrinho'):
            self.request.session['carrinho'] = {}

        return self.request.session['carrinho']

    def atualiza_precos_carrinho(self):
        """Atualiza os preços quantitativos do carrinho"""
        carrinho = self.get_carrinho()

        for linha in carrinho.values():
            # cálculos do preco total de cada produto
            linha['preco_quantitativo'] = \
                linha['preco_unitario'] * \
                linha['quantidade']
            linha['preco_quantitativo_promocional'] = \
                linha['preco_unitario_promocional'] * \
                linha['quantidade']

    def remover_produto_carrinho(self, variacao_id: str, quant: int = 1):
        carrinho = self.get_carrinho()

        if not carrinho:
            return
        if not carrinho.get(variacao_id):
            return

        quant = int(quant) if quant >= 0 else 0
        carrinho[variacao_id]['quantidade'] -= quant

        if carrinho[variacao_id]['quantidade'] <= 0:
            del carrinho[variacao_id]
        else:
            self.atualiza_precos_carrinho()

    def adicionar_produto_carrinho(self, variacao: models.Variacao, quant: int = 1):
        """Adiciona um novo produto ao carrinho e/ou seta a quantidade.

        Args:
            variacao (Variacao): objeto Variacao.
            quant (int): quantidade a ser adicionada (inteiro positivo).
        """
        variacao_id = str(variacao.id)
        carrinho = self.get_carrinho()

        quant = int(quant) if quant >= 0 else 0

        if variacao_id in carrinho:
            carrinho[variacao_id]['quantidade'] += quant
        else:
            produto = variacao.produto
            carrinho[variacao_id] = {
                'produto_id': produto.id,
                'produto_nome': produto.nome,
                'variacao_nome': variacao.nome,
                'variacao_id': variacao.id,
                'preco_unitario': variacao.preco,
                'preco_unitario_promocional': variacao.preco_promocional,
                'preco_quantitativo': 0,
                'preco_quantitativo_promocional': 0,
                'quantidade': quant,
                'slug': produto.slug,
                'imagem': produto.imagem.url if produto.imagem else None,
            }

        car_var = carrinho[variacao_id]

        # quantidade maior que estoque
        sem_estoque = False
        if variacao.estoque < car_var['quantidade']:
            car_var['quantidade'] = variacao.estoque
            if variacao.estoque == 0:
                del carrinho[variacao_id]
            sem_estoque = True

        self.atualiza_precos_carrinho()

        if sem_estoque:
            produto = variacao.produto
            raise SemEstoqueError(
                f'Estoque insuficiente para '
                f'{car_var["quantidade"]}x no produto '
                f'"{produto.nome} ({variacao.nome})". Adicionamos '
                f'{variacao.estoque}x ao seu carrinho.'
            )

    def salva_carrinho(self):
        self.request.session.save()


class ListaProdutos(ListView):
    model = models.Produto
    template_name = 'produto/listaprodutos.html'
    context_object_name = 'produtos'
    paginate_by = 1
    ordering = ['-id']

    def get_queryset(self):
        sql = '''
            SELECT *, MIN(variacao.preco) as preco FROM produto
                INNER JOIN variacao ON produto.id=variacao.produto_id
                GROUP BY variacao.produto_id ORDER BY variacao.produto_id DESC;
        '''
        produtos = models.Produto.objects.raw(sql)

        return produtos


class DetalheProduto(DetailView):
    model = models.Produto
    template_name = 'produto/detalheproduto.html'
    context_object_name = 'produto'
    slug_url_kwarg = 'slug'

    def get_queryset(self):
        qs = super().get_queryset()
        # TODO: Exibir "Sem estoque" na página do produto
        # qs = qs.annotate(
        #     existe_estoque=Count(
        #         Case(
        #             When(variacao__produto_id=F('pk'),
        #                  variacao__estoque__gt=0, then=F('variacao__estoque'))
        #         )
        #     )
        # )
        # print(qs.query)
        return qs


class Carrinho(View):
    def get(self, *args, **kwargs):
        return render(self.request, 'produto/carrinho.html')


class AdicionarAoCarrinho(CarrinhoMixin, View):
    def get(self, *args, **kwargs):
        http_referer = self.request.META.get(
            'HTTP_REFERER', reverse('produto:listaprodutos'))
        variacao_id = self.request.GET.get('vid')

        if not variacao_id:
            messages.error(self.request, 'Produto não existe.')
            return redirect(http_referer)

        variacao = get_object_or_404(models.Variacao, pk=variacao_id)

        try:
            self.adicionar_produto_carrinho(variacao)
        except SemEstoqueError as err:
            messages.error(self.request, *err.args)
        else:
            car_var = self.get_carrinho()[variacao_id]
            messages.success(
                self.request,
                f'Produto {car_var["produto_nome"]} adicionado ao seu '
                f'carrinho. Possui {car_var["quantidade"]}x.'
            )

        self.salva_carrinho()

        return redirect(http_referer)


class RemoverDoCarrinho(CarrinhoMixin, View):
    def get(self, *args, **kwargs):
        http_referer = self.request.META.get(
            'HTTP_REFERER', reverse('produto:listaprodutos'))
        variacao_id = self.request.GET.get('vid')

        variacao = get_object_or_404(models.Variacao, pk=variacao_id)

        self.remover_produto_carrinho(variacao.pk)
        self.salva_carrinho()

        messages.success(
            self.request,
            f'Produto {variacao.produto.nome} removido do seu carrinho'
        )

        return redirect(http_referer)


class ResumoDaCompra(DispatchLoginRequiredMixin, CarrinhoMixin, View):
    def get(self, request: HttpRequest, *args, **kwargs):
        http_referer = request.META.get(
            'HTTP_REFERER', reverse('produto:resumodacompra'))

        if not self.get_carrinho():
            return redirect(reverse('produto:listaprodutos'))

        enderecos = Endereco.objects.filter(
            perfil_id=self.request.user.perfil.pk)
        usuario = self.request.user

        if not enderecos:
            messages.error(
                request,
                mark_safe(
                    'Sem endereços disponíveis. Cadastre um novo '
                    f'<a href="{reverse("perfil:registrarendereco")}">aqui</a>'
                    ' para finalizar a compra.'
                )
            )
            return redirect(http_referer)

        return render(self.request, 'produto/resumodacompra.html', {
            'enderecos': enderecos,
            'usuario': usuario,
        })


class Busca(ListaProdutos):
    model = models.Produto
    template_name = 'produto/busca.html'

    def get_queryset(self):
        termo = self.request.GET.get('termo') or self.request.session['termo']
        
        self.request.session['termo'] = termo

        # Na nota diz:
        # "Dictionary params are not supported with the SQLite backend; with
        # this backend, you must pass parameters as a list."
        # https://docs.djangoproject.com/en/3.2/topics/db/sql/#passing-parameters-into-raw
        sql = '''
            SELECT *, MIN(variacao.preco) as preco FROM produto
                INNER JOIN variacao ON produto.id=variacao.produto_id
                WHERE 
                    (produto.nome LIKE %(t)s OR 
                    produto.descricao_curta LIKE %(t)s OR 
                    produto.descricao_longa LIKE %(t)s)
                GROUP BY variacao.produto_id 
                ORDER BY variacao.produto_id DESC;
        '''
        produtos = models.Produto.objects.raw(sql, params={'t': f'%{termo}%'})

        return produtos

produto/templates/produto/busca.html
{% extends 'produto/listaprodutos.html' %}

{% block titulo %}{{ request.GET.termo }} | {% endblock %}

produto/templates/produto/carrinho.html
{% extends 'base.html' %}

{% load vffilters %}

{% block titulo %}Carrinho | {% endblock %}

{% block conteudo %}

{% if request.session.carrinho|length %}
<div class="row mt-3">
    <div class="col">
        <h3>Carrinho de compras</h3>
        <p class="lead">Os produtos, quantidades e preços que você escolheu.</p>
        {% include 'includes/_carrinho.html' %}
    </div>
</div>

<div class="row mt-3">
    <div class="col-lg">
        <p class='lead'>Total no carrinho</p>

        <div class='table-responsive'>
            <table class="table">
                <tr>
                    <td class="font-weight-bold">Total</td>
                    <td>{{ request.session.carrinho|calcula_total_carrinho|formata_dinheiro }}</td>
                </tr>
            </table>
        </div>
    </div>
    <div class="col-lg mt-auto">
        <a class="btn btn-lg btn-block btn-primary" href="{% url 'produto:resumodacompra' %}">
            Finalizar a compra
        </a>
    </div>
</div>
{% else %}
<div class="row mt-3">
    <div class="col">
        <h3>Carrinho vazio</h3>
        <p class="lead">Não há produtos em seu carrinho.</p>
    </div>
</div>
{% endif %}

{% endblock %}

produto/templates/produto/detalheproduto.html
{% extends 'base.html' %}
{% load vffilters %}

{% block titulo %}{{ produto.nome }} | {% endblock %}

{% block conteudo %}
<div class="row">
    <div class="col-lg-12">
        <div class="row">
            <div class="col-lg">
                <div class="row no-gutters">
                    <div class="col-lg-12">
                        {% if produto.imagem %}
                        <img class="img-fluid" src="{{ produto.imagem.url }}">
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-lg">
                <div class="mt-4 mt-lg-0">
                    <h1 class="h2">{{ produto.nome }}</h1>
                    <p class="lead">{{ produto.descricao_curta|linebreaks }}</p>
                    <p class="lead">
                        <span id="variation-preco" class="lead product-price"></span>
                        <span id="variation-preco-muted" class="lead product-old-price text-muted"></span>
                    </p>

                    <form method="get" action="{% url 'produto:adicionaraocarrinho' %}" id="form-add-to-cart">
                        <div class="form-group">
                            <select id="select-variacoes" name="vid" class="form-control form-control-lg">
                                {% for variacao in produto.variacao_set.all %}
                                {% if variacao.preco_promocional %}
                                <option data-preco="{{ variacao.preco|formata_dinheiro }}"
                                    data-preco-promocional="{{ variacao.preco_promocional|formata_dinheiro }}"
                                    value="{{ variacao.pk }}">{{ variacao.nome }}</option>
                                {% else %}
                                <option data-preco="{{ variacao.preco|formata_dinheiro }}" value="{{ variacao.pk }}">
                                    {{ variacao.nome }}</option>
                                {% endif %}
                                {% endfor %}
                            </select>
                        </div>

                        <div class="text-left">
                            <button type="submit" class="btn btn-primary btn-lg btn-block">
                                <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                Adicionar ao carrinho
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="mt-5 mb-5">
                    <h2 class="text-center">{{ produto.nome }}</h2>
                    {{ produto.descricao_longa|linebreaks }}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

produto/templates/produto/listaprodutos.html
{% extends 'base.html' %}

{% load vffilters %}

{% block titulo %}Produtos | {% endblock %}

{% block conteudo %}
<div class="row">
    <div class="col-lg-12">
        <div class="card-columns">
            {% for produto in produtos %}
            <div class="card">
                {% if produto.imagem %}
                <a href="{% url 'produto:detalheproduto' produto.slug %}">
                    <img class="card-img-top" src="{{ produto.imagem.url }}" alt="{{ produto.nome }}">
                </a>
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title">{{ produto.nome }}</h5>
                    <p class="card-text">{{ produto.descricao_curta }}</p>
                    <div class="container product-price-block text-center">
                        {% if produto.preco_promocional and produto.preco_promocional > 0 %}
                        <span class="product-price">
                            {{ produto.preco_promocional|formata_dinheiro }}
                        </span>
                        <span class="product-old-price text-muted">
                            {{ produto.preco|formata_dinheiro }}
                        </span>
                        {% else %}
                        <span class="product-price">
                            {{ produto.preco|formata_dinheiro }}
                        </span>
                        {% endif %}
                    </div>
                </div>
                <div class="card-footer bg-transparent border-top-light-custom text-center">
                    <a href="{% url 'produto:detalheproduto' produto.slug %}"
                        class="btn btn-primary btn-sm m-1 btn-block">
                        <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                        Comprar
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

<div class="row mt-3">
    <div class="col">
        {% include 'includes/_pagination.html' %}
    </div>
</div>
{% endblock %}

produto/templates/produto/resumodacompra.html
{% extends 'base.html' %}

{% load vffilters %}

{% block titulo %}Resumo da compra | {% endblock %}

{% block conteudo %}
<div class="row mb-5">
    <div class="col-lg">
        <h2>Resumo da sua compra</h2>
        <p class="lead">Dados do usuário</p>
        <p>Caso precise editar, <a href="{% url 'perfil:atualizar' %}">clique aqui</a></p>

        <dl class="row">
            <dt class="col-lg-2">Nome:</dt>
            <dd class="col-lg-4">{{ usuario.first_name }}</dd>
            <dt class="col-lg-2">Sobrenome:</dt>
            <dd class="col-lg-4">{{ usuario.last_name }}</dd>

            <dt class="col-lg-2">Idade:</dt>
            <dd class="col-lg-4">{{ usuario.perfil.data_nascimento|get_idade }}</dd>
            <dt class="col-lg-2">Nascimento:</dt>
            <dd class="col-lg-4">{{ usuario.perfil.data_nascimento }}</dd>

            <dt class="col-lg-2">CPF:</dt>
            <dd class="col-lg-4">{{ usuario.perfil.cpf }}</dd>
            <dt class="col-lg-2">E-mail:</dt>
            <dd class="col-lg-4">{{ usuario.email }}</dd>
        </dl>

        <!-- TODO: Fazer o javascript para consultar e exibir os endereços de acordo com o que o cliente escolher -->
        <p class="lead">Dados de endereço</p>
        <div class="form-group">
            <select id="select-enderecos" name="eid" class="form-control form-control-lg">
                {% for endereco in enderecos %}
                <option value="{{ endereco.pk }}">{{ endereco.apelido }}</option>
                {% endfor %}
            </select>
        </div>

        <dl class="row">
            <dt class="col-lg-2">Endereço:</dt>
            <dd class="col-lg-4">Av. Filho Junior</dd>
            <dt class="col-lg-2">Número:</dt>
            <dd class="col-lg-4">12</dd>

            <dt class="col-lg-2">Complemento:</dt>
            <dd class="col-lg-4">Casa</dd>
            <dt class="col-lg-2">Nascimento:</dt>
            <dd class="col-lg-4">Centro</dd>

            <dt class="col-lg-2">Cidade:</dt>
            <dd class="col-lg-4">São Paulo</dd>
            <dt class="col-lg-2">Estado:</dt>
            <dd class="col-lg-4">SP</dd>

            <dt class="col-lg-2">CEP:</dt>
            <dd class="col-lg-4">00000000</dd>
        </dl>
    </div>
</div>

{% include 'includes/_carrinho.html' %}

<div class="row">
    <div class="col">
        <a class="btn btn-block btn-primary btn-lg" href="{% url 'pedido:salvarpedido' %}">
            Realizar pedido e pagar
        </a>
    </div>
</div>
{% endblock %}